name: CI_version-2.01

on:
  push:
    paths-ignore:
      - "**/README.rst"
      - "**/dependabot.yml"
    branches: [version-2.01]
  pull_request:
    paths-ignore:
      - "**/README.rst"
      - "**/dependabot.yml"
    branches: [version-2.01]

concurrency: CI-2.01

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Checkout Schemas repo
        uses: actions/checkout@v4
        with:
          repository: IATI/IATI-Schemas
          ref: version-2.01
          path: IATI-Schemas

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install libxml2-utils python3-dev python3-lxml
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt

      - name: Run schema validation with xmllint
        run: |
          xmllint --schema IATI-Schemas/iati-activities-schema.xsd --noout en/activity-standard/*.xml
          xmllint --schema IATI-Schemas/iati-organisations-schema.xsd --noout en/organisation-standard/*.xml

      - name: Build and test
        run: |
          cd en
          make dirhtml
          cd ..
          cd fr
          make dirhtml
          cd ..
          pytest tests

  automerge:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.10
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
